#ifndef DEFINE_H
#define DEFINE_H

	//BUNKER//
enum EstadoBunker { INTEIRO, AVARIADO, DESTRUIDO };

#define PEDACOS_ALTURA 5
#define PEDACOS_LARGURA 5





	//ALIENS//
#define LINHAS_TROPA 2
#define COLUNAS_TROPA 10
#define DISTANCIA_PASSO 1
#define ALTURA_NAVE 40
#define LARGURA_NAVE 40


	//MISSIL//
enum SENTIDO { CIMA, BAIXO };
#define VELOCIDADE_MISSIL_SPACESHIP 5
#define VELOCIDADE_MISSIL_ALIEN 5

	//SPACESHIP//

enum DIRECAO { ESQUERDA, DIREITA, ALIEN_CIMA, ALIEN_BAIXO };
#define LARGURA_SPACESHIP 53
#define ALTURA_SPACESHIP  76
#define DELTA_X (-LARGURA_SPACESHIP/2)
#define DELTA_Y (-ALTURA_SPACESHIP)

 //JOGO//

#define DISPLAY_WIDTH 640
#define DISPLAY_HEIGHT 480
#define FPS 60
#define N_TECLAS 3
#define LIMITE_DIREITO 630
#define LIMITE_ESQUERDO -20




#endif
