#ifndef DEFINE_H
#define DEFINE_H

	//BUNKER//
enum EstadoBunker { INTEIRO, AVARIADO, DESTRUIDO };

#define PEDACOS_ALTURA 5
#define PEDACOS_LARGURA 5
#define LARGURA_BUNKER 100
#define ALTURA_BUNKER 80
#define N_BUNKERS 5

	//INIMIGOS//
#define LINHAS_TROPA 4
#define COLUNAS_TROPA 8
#define DISTANCIA_PASSO 1
#define ALTURA_NAVE 40
#define LARGURA_NAVE 40
#define MAX_DESTROYERS 5


	//MISSIL//
enum SENTIDO { CIMA, BAIXO };
#define VELOCIDADE_MISSIL_SPACESHIP 5
#define VELOCIDADE_MISSIL_INIMIGO 5
#define MAX_MISSEIS 100

	//SPACESHIP//

enum DIRECAO { ESQUERDA, DIREITA, ALIEN_CIMA, ALIEN_BAIXO };
#define LARGURA_SPACESHIP 53
#define ALTURA_SPACESHIP  76
#define DELTA_X (-LARGURA_SPACESHIP/2)
#define DELTA_Y (-ALTURA_SPACESHIP)

 	//JOGO//

#define DISPLAY_WIDTH 1024
#define DISPLAY_HEIGHT 640
#define FPS 60
#define N_TECLAS 3
#define TAMANHO_FONTE 30
#define CINZA_CLARO 105,105,105
#define VERDE_CLARO 0,128,0

	//VIDAS//
#define N_VIDAS 4
#define POSICAO_Y_VIDA 30


	//PLACAR//
#define POSICAO_X_PLACAR 10
#define POSICAO_Y_PLACAR 20

#endif
